GET http://localhost:3001/api/notes

### seperator
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS Code REST Client is a plug for sending requests",
    "important": false
}